CareerCloudCoreUI/Controllers/CompanyJobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CareerCloud.EntityFrameworkDataAccess;
using CareerCloud.Pocos;

namespace CareerCloudCoreUI.Controllers
{
    public class CompanyJobController : Controller
    {
        private readonly CareerCloudContext _context;

        public CompanyJobController(CareerCloudContext context)
        {
            _context = context;
        }

        // GET: CompanyJob
        public async Task<IActionResult> Index(Guid? Id)
        {
            var careerCloudContext = _context.CompanyJobs.Where(a => a.Company == Id);
            return View(await careerCloudContext.ToListAsync());
        }

        // GET: CompanyJob/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyJobPoco = await _context.CompanyJobs
                .Include(c => c.CompanyProfiles)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (companyJobPoco == null)
            {
                return NotFound();
            }

            return View(companyJobPoco);
        }

        // GET: CompanyJob/Create
        public IActionResult Create()
        {
            ViewData["Company"] = new SelectList(_context.CompanyProfiles, "Id", "Id");
            return View();
        }

        // POST: CompanyJob/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Company,ProfileCreated,IsInactive,IsCompanyHidden,TimeStamp")] CompanyJobPoco companyJobPoco)
        {
            if (ModelState.IsValid)
            {
                companyJobPoco.Id = Guid.NewGuid();
                _context.Add(companyJobPoco);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Company"] = new SelectList(_context.CompanyProfiles, "Id", "Id", companyJobPoco.Company);
            return View(companyJobPoco);
        }

        // GET: CompanyJob/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyJobPoco = await _context.CompanyJobs.FindAsync(id);
            if (companyJobPoco == null)
            {
                return NotFound();
            }
            ViewData["Company"] = new SelectList(_context.CompanyProfiles, "Id", "Id", companyJobPoco.Company);
            return View(companyJobPoco);
        }

        // POST: CompanyJob/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Company,ProfileCreated,IsInactive,IsCompanyHidden,TimeStamp")] CompanyJobPoco companyJobPoco)
        {
            if (id != companyJobPoco.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(companyJobPoco);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyJobPocoExists(companyJobPoco.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Company"] = new SelectList(_context.CompanyProfiles, "Id", "Id", companyJobPoco.Company);
            return View(companyJobPoco);
        }

        // GET: CompanyJob/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyJobPoco = await _context.CompanyJobs
                .Include(c => c.CompanyProfiles)

                .FirstOrDefaultAsync(m => m.Id == id);
            if (companyJobPoco == null)
            {
                return NotFound();
            }

            return View(companyJobPoco);
        }

        // POST: CompanyJob/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid? id)
        {
            var companyJobPoco = await _context.CompanyJobs.FindAsync(id);
            _context.CompanyJobs.Remove(companyJobPoco);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompanyJobPocoExists(Guid? id)
        {
            return _context.CompanyJobs.Any(e => e.Id == id);
        }
    }
}

CareerCloudCoreUI/Controllers/CompanyLocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CareerCloud.EntityFrameworkDataAccess;
using CareerCloud.Pocos;

namespace CareerCloudCoreUI.Controllers
{
    public class CompanyLocationController : Controller
    {
        private readonly CareerCloudContext _context;

        public CompanyLocationController(CareerCloudContext context)
        {
            _context = context;
        }

        // GET: CompanyLocation
        public async Task<IActionResult> Index(Guid? Id)
        {
            var careerCloudContext = _context.CompanyLocations.Include(c => c.CompanyProfiles).Where(c=>c.CompanyProfiles.Id == Id);
            return View(await careerCloudContext.ToListAsync());
        }

        // GET: CompanyLocation/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyLocationPoco = await _context.CompanyLocations
                .Include(c => c.CompanyProfiles)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (companyLocationPoco == null)
            {
                return NotFound();
            }

            return View(companyLocationPoco);
        }

        // GET: CompanyLocation/Create
        public IActionResult Create()
        {
            ViewData["Company"] = new SelectList(_context.CompanyProfiles, "Id", "Id");
            return View();
        }

        // POST: CompanyLocation/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Company,CountryCode,Province,Street,City,PostalCode,TimeStamp")] CompanyLocationPoco companyLocationPoco)
        {
            if (ModelState.IsValid)
            {
                companyLocationPoco.Id = Guid.NewGuid();
                _context.Add(companyLocationPoco);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Company"] = new SelectList(_context.CompanyProfiles, "Id", "Id", companyLocationPoco.Company);
            return View(companyLocationPoco);
        }

        // GET: CompanyLocation/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyLocationPoco = await _context.CompanyLocations.FindAsync(id);
            if (companyLocationPoco == null)
            {
                return NotFound();
            }
            ViewData["Company"] = new SelectList(_context.CompanyProfiles, "Id", "Id", companyLocationPoco.Company);
            return View(companyLocationPoco);
        }

        // POST: CompanyLocation/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Company,CountryCode,Province,Street,City,PostalCode,TimeStamp")] CompanyLocationPoco companyLocationPoco)
        {
            if (id != companyLocationPoco.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(companyLocationPoco);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyLocationPocoExists(companyLocationPoco.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Company"] = new SelectList(_context.CompanyProfiles, "Id", "Id", companyLocationPoco.Company);
            return View(companyLocationPoco);
        }

        // GET: CompanyLocation/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyLocationPoco = await _context.CompanyLocations
                .Include(c => c.CompanyProfiles)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (companyLocationPoco == null)
            {
                return NotFound();
            }

            return View(companyLocationPoco);
        }

        // POST: CompanyLocation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid? id)
        {
            var companyLocationPoco = await _context.CompanyLocations.FindAsync(id);
            _context.CompanyLocations.Remove(companyLocationPoco);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompanyLocationPocoExists(Guid? id)
        {
            return _context.CompanyLocations.Any(e => e.Id == id);
        }
    }
}

CareerCloudCoreUI/Controllers/CompanyProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CareerCloud.EntityFrameworkDataAccess;
using CareerCloud.Pocos;

namespace CareerCloudCoreUI.Controllers
{
    public class CompanyProfileController : Controller
    {
        private readonly CareerCloudContext _context;

        public CompanyProfileController(CareerCloudContext context)
        {
            _context = context;
        }

        // GET: CompanyProfile
        public async Task<IActionResult> Index()
        {
            return View(await _context.CompanyProfiles.ToListAsync());
        }

        // GET: CompanyProfile/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyProfilePoco = await _context.CompanyProfiles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (companyProfilePoco == null)
            {
                return NotFound();
            }

            return View(companyProfilePoco);
        }

        // GET: CompanyProfile/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CompanyProfile/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,RegistrationDate,CompanyWebsite,ContactPhone,ContactName,CompanyLogo,TimeStamp")] CompanyProfilePoco companyProfilePoco)
        {
            if (ModelState.IsValid)
            {
                companyProfilePoco.Id = Guid.NewGuid();
                _context.Add(companyProfilePoco);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(companyProfilePoco);
        }

        // GET: CompanyProfile/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyProfilePoco = await _context.CompanyProfiles.FindAsync(id);
            if (companyProfilePoco == null)
            {
                return NotFound();
            }
            return View(companyProfilePoco);
        }

        // POST: CompanyProfile/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,RegistrationDate,CompanyWebsite,ContactPhone,ContactName,CompanyLogo,TimeStamp")] CompanyProfilePoco companyProfilePoco)
        {
            if (id != companyProfilePoco.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(companyProfilePoco);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyProfilePocoExists(companyProfilePoco.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(companyProfilePoco);
        }

        // GET: CompanyProfile/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyProfilePoco = await _context.CompanyProfiles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (companyProfilePoco == null)
            {
                return NotFound();
            }

            return View(companyProfilePoco);
        }

        // POST: CompanyProfile/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid? id)
        {
            var companyProfilePoco = await _context.CompanyProfiles.FindAsync(id);
            _context.CompanyProfiles.Remove(companyProfilePoco);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompanyProfilePocoExists(Guid? id)
        {
            return _context.CompanyProfiles.Any(e => e.Id == id);
        }
    }
}

CareerCloudCoreUI/Views/CompanyProfile/Create.cshtml
@model CareerCloud.Pocos.CompanyProfilePoco

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CompanyProfilePoco</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RegistrationDate" class="control-label"></label>
                <input asp-for="RegistrationDate" class="form-control" />
                <span asp-validation-for="RegistrationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyWebsite" class="control-label"></label>
                <input asp-for="CompanyWebsite" class="form-control" />
                <span asp-validation-for="CompanyWebsite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactPhone" class="control-label"></label>
                <input asp-for="ContactPhone" class="form-control" />
                <span asp-validation-for="ContactPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactName" class="control-label"></label>
                <input asp-for="ContactName" class="form-control" />
                <span asp-validation-for="ContactName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyLogo" class="control-label"></label>
                <input asp-for="CompanyLogo" class="form-control" />
                <span asp-validation-for="CompanyLogo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CareerCloudCoreUI/Views/CompanyProfile/Delete.cshtml
@model CareerCloud.Pocos.CompanyProfilePoco

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CompanyProfilePoco</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegistrationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyWebsite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyWebsite)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyLogo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyLogo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeStamp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CareerCloudCoreUI/Views/CompanyProfile/Details.cshtml
@model CareerCloud.Pocos.CompanyProfilePoco

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CompanyProfilePoco</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegistrationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyWebsite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyWebsite)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyLogo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyLogo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeStamp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CareerCloudCoreUI/Views/CompanyProfile/Edit.cshtml
@model CareerCloud.Pocos.CompanyProfilePoco

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CompanyProfilePoco</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="RegistrationDate" class="control-label"></label>
                <input asp-for="RegistrationDate" class="form-control" />
                <span asp-validation-for="RegistrationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyWebsite" class="control-label"></label>
                <input asp-for="CompanyWebsite" class="form-control" />
                <span asp-validation-for="CompanyWebsite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactPhone" class="control-label"></label>
                <input asp-for="ContactPhone" class="form-control" />
                <span asp-validation-for="ContactPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactName" class="control-label"></label>
                <input asp-for="ContactName" class="form-control" />
                <span asp-validation-for="ContactName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyLogo" class="control-label"></label>
                <input asp-for="CompanyLogo" class="form-control" />
                <span asp-validation-for="CompanyLogo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CareerCloudCoreUI/Views/CompanyProfile/Index.cshtml
@model IEnumerable<CareerCloud.Pocos.CompanyProfilePoco>

@{
    ViewData["Title"] = "Company Profiles";
}

<h2>Company Profiles</h2>

<p>
    <a asp-controller="CompanyProfile" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Date of Registration
                @*@Html.DisplayNameFor(model => model.RegistrationDate)*@
            </th>
            <th>
                Company Website
                @*@Html.DisplayNameFor(model => model.CompanyWebsite)*@
            </th>
            <th>
                Contact Number
                @*@Html.DisplayNameFor(model => model.ContactPhone)*@
            </th>
            <th>
                Contact Person
                @*@Html.DisplayNameFor(model => model.ContactName)*@
            </th>
            <th>
                Company Logo
                @*@Html.DisplayNameFor(model => model.CompanyLogo)*@
            </th>

            <th>Options</th>
            <th>Company Details</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RegistrationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyWebsite)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactPhone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyLogo)
            </td>

            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> <br />
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> <br />
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>

            <td>
                <a asp-controller="CompanyDescription" asp-action="Index" asp-route-id="@item.Id">Description</a> <br />
                <a asp-controller="CompanyJob" asp-action="Index" asp-route-id="@item.Id">Job</a> <br />
                <a asp-controller="CompanyLocation" asp-action="Index" asp-route-id="@item.Id">Location</a>
               



            </td>
        </tr>
}
    </tbody>
</table>